/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import javax.swing.JOptionPane;
import locadora.Motorista;
/**
 *
 * @author leorb
 */
public class TelaMotorista extends javax.swing.JFrame {

    static Motorista motorista;
    /**
     * Creates new form TelaMotorista
     */
    public TelaMotorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosMotorista = new javax.swing.JPanel();
        lblIdMotorista = new javax.swing.JLabel();
        lblNomeMotorista = new javax.swing.JLabel();
        lblTelefoneMotorista = new javax.swing.JLabel();
        lblCNH = new javax.swing.JLabel();
        txtIdMotorista = new javax.swing.JTextField();
        txtNomeMotorista = new javax.swing.JTextField();
        txtTelefoneMotorista = new javax.swing.JTextField();
        txtCNH = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Motorista");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/drivingDriverSmall.png")).getImage());

        pnlDadosMotorista.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações do motorista", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 13))); // NOI18N

        lblIdMotorista.setText("Id do motorista:");

        lblNomeMotorista.setText("Nome do motorista:");

        lblTelefoneMotorista.setText("Telefone do motorista:");

        lblCNH.setText("CNH do motorista:");

        txtIdMotorista.setToolTipText("Insira o id do motorista");
        txtIdMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMotoristaActionPerformed(evt);
            }
        });

        txtNomeMotorista.setToolTipText("Insira o nome do motorista");
        txtNomeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMotoristaActionPerformed(evt);
            }
        });

        txtTelefoneMotorista.setToolTipText("Insira o telefone do motorista");

        txtCNH.setToolTipText("Insira a CNH do motorista");

        javax.swing.GroupLayout pnlDadosMotoristaLayout = new javax.swing.GroupLayout(pnlDadosMotorista);
        pnlDadosMotorista.setLayout(pnlDadosMotoristaLayout);
        pnlDadosMotoristaLayout.setHorizontalGroup(
            pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosMotoristaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDadosMotoristaLayout.createSequentialGroup()
                        .addComponent(lblNomeMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeMotorista))
                    .addGroup(pnlDadosMotoristaLayout.createSequentialGroup()
                        .addComponent(lblTelefoneMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosMotoristaLayout.createSequentialGroup()
                        .addComponent(lblIdMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosMotoristaLayout.createSequentialGroup()
                        .addComponent(lblCNH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        pnlDadosMotoristaLayout.setVerticalGroup(
            pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosMotoristaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMotorista)
                    .addComponent(txtIdMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeMotorista)
                    .addComponent(txtNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneMotorista)
                    .addComponent(txtTelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNH)
                    .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDadosMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDadosMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMotoristaActionPerformed

    private void txtNomeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMotoristaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtIdMotorista.getText().equals("") || txtNomeMotorista.getText().equals("") 
        || txtTelefoneMotorista.getText().equals("") || txtCNH.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int id = Integer.parseInt(txtIdMotorista.getText());
            String nome = txtNomeMotorista.getText();
            String tel = txtTelefoneMotorista.getText();
            String cnh = txtCNH.getText();

            motorista = new Motorista(id, nome, tel, cnh);

            JOptionPane.showMessageDialog(null, "Motorista registrado!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);

            this.setVisible(false);
       }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCNH;
    private javax.swing.JLabel lblIdMotorista;
    private javax.swing.JLabel lblNomeMotorista;
    private javax.swing.JLabel lblTelefoneMotorista;
    private javax.swing.JPanel pnlDadosMotorista;
    private javax.swing.JTextField txtCNH;
    private javax.swing.JTextField txtIdMotorista;
    private javax.swing.JTextField txtNomeMotorista;
    private javax.swing.JTextField txtTelefoneMotorista;
    // End of variables declaration//GEN-END:variables
}
