
package telas;

import fourseasoning.Conta;
import fourseasoning.Funcionario;
import java.awt.Color;
import static fourseasoning.Funcionario.getContas;
import static fourseasoning.Funcionario.getGerente;
import fourseasoning.Mesa;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import fourseasoning.Pedido;
import java.util.Arrays;
import static telas.TelaMesa.tela;

public class TelaConta extends javax.swing.JFrame {
    static ArrayList<Conta> contas = getContas();
    static Funcionario gerente = getGerente();
    static Conta conta = new Conta();
    static Pedido pedido = new Pedido();
    /**
     * Creates new form TelaConta
     */
    public TelaConta() {
        initComponents();
        // Troca a cor do JFrame
        Color cor = new Color(217,220,235);
        getContentPane().setBackground(cor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnPrincipal = new javax.swing.JLayeredPane();
        pnlNovaConta = new javax.swing.JPanel();
        pnlNovaConta.setVisible(false);
        txtEmailN = new javax.swing.JTextField();
        lblSenhaN = new javax.swing.JLabel();
        txtDepositoN = new javax.swing.JTextField();
        lblCSenhaN = new javax.swing.JLabel();
        lblDepositoN = new javax.swing.JLabel();
        lblCategoriaN = new javax.swing.JLabel();
        cbbCategoriaN = new javax.swing.JComboBox<>();
        txtSenhaN = new javax.swing.JPasswordField();
        txtCSenhaN = new javax.swing.JPasswordField();
        lblGeneroN = new javax.swing.JLabel();
        lblNomeN = new javax.swing.JLabel();
        txtNomeN = new javax.swing.JTextField();
        lblCpfN = new javax.swing.JLabel();
        txtCpfN = new javax.swing.JTextField();
        lblTelefoneN = new javax.swing.JLabel();
        txtTelefoneN = new javax.swing.JTextField();
        lblEmailN = new javax.swing.JLabel();
        cbbGeneroN = new javax.swing.JComboBox<>();
        lblErroN = new javax.swing.JLabel();
        lblErroN.setVisible(false);
        btnVoltarN = new javax.swing.JButton();
        btnConfirmarN = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        pnlLogin.setVisible(false);
        lblCpfL = new javax.swing.JLabel();
        lblSenhaL = new javax.swing.JLabel();
        txtSenhaL = new javax.swing.JPasswordField();
        txtCpfL = new javax.swing.JTextField();
        lblErroL = new javax.swing.JLabel();
        lblErroL.setVisible(false);
        btnVoltarL = new javax.swing.JButton();
        btnLoginL = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        btnNovaConta = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lpnConta = new javax.swing.JLayeredPane();
        pnlConta = new javax.swing.JPanel();
        pnlConta.setVisible(false);
        pnlConta.setAlignmentY(0);
        lblSaldo = new javax.swing.JLabel();
        btnSaldo = new javax.swing.JToggleButton();
        btnConfig = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnPedido.setHorizontalTextPosition(JButton.CENTER);
        btnPedido.setVerticalTextPosition(JButton.TOP);
        btnPedido.setIconTextGap(10);
        txtDeposito = new javax.swing.JTextField();
        txtDeposito.setVisible(false);
        btnSair = new javax.swing.JButton();
        btnSair.setHorizontalTextPosition(JButton.CENTER); btnSair.setVerticalTextPosition(JButton.TOP); btnSair.setIconTextGap(10);
        btnConfirmarD = new javax.swing.JButton();
        btnConfirmarD.setVisible(false);
        lblAvisoD = new javax.swing.JLabel();
        lblPagar = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        lblPago = new javax.swing.JLabel();
        if(conta.isPago()){
            lblPagar.setVisible(true);
        }else{
            lblPagar.setVisible(false);
        }
        btnVerFatura = new javax.swing.JButton();
        pnlConfig = new javax.swing.JPanel();
        pnlConfig.setVisible(false);
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        cbbGenero = new javax.swing.JComboBox<>();
        cbbCategoria = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        setBackground(new java.awt.Color(217, 220, 235));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente32.png")).getImage());
        setPreferredSize(new java.awt.Dimension(960, 720));

        lpnPrincipal.setBackground(new java.awt.Color(217, 220, 235));
        lpnPrincipal.setForeground(new java.awt.Color(217, 220, 235));
        lpnPrincipal.setPreferredSize(new java.awt.Dimension(960, 534));

        pnlNovaConta.setBackground(new java.awt.Color(217, 220, 235));
        pnlNovaConta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscrever-se", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(66, 33, 99))); // NOI18N
        pnlNovaConta.setForeground(new java.awt.Color(217, 220, 235));

        txtEmailN.setBackground(new java.awt.Color(204, 204, 230));
        txtEmailN.setForeground(new java.awt.Color(66, 33, 99));
        txtEmailN.setToolTipText("Digite o email do cliente");

        lblSenhaN.setForeground(new java.awt.Color(66, 33, 99));
        lblSenhaN.setText("Senha:");

        txtDepositoN.setBackground(new java.awt.Color(204, 204, 230));
        txtDepositoN.setForeground(new java.awt.Color(66, 33, 99));
        txtDepositoN.setToolTipText("Digite o valor que o cliente depositará");

        lblCSenhaN.setForeground(new java.awt.Color(66, 33, 99));
        lblCSenhaN.setText("Confirmar Senha:");

        lblDepositoN.setForeground(new java.awt.Color(66, 33, 99));
        lblDepositoN.setText("Depósito Inicial:");

        lblCategoriaN.setForeground(new java.awt.Color(66, 33, 99));
        lblCategoriaN.setText("Categoria:");

        cbbCategoriaN.setBackground(new java.awt.Color(217, 220, 235));
        cbbCategoriaN.setForeground(new java.awt.Color(66, 33, 99));
        cbbCategoriaN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Basic", "Standard", "Premium" }));
        cbbCategoriaN.setBorder(null);

        txtSenhaN.setBackground(new java.awt.Color(204, 204, 230));
        txtSenhaN.setForeground(new java.awt.Color(66, 33, 99));
        txtSenhaN.setToolTipText("Digite a senha do cliente");

        txtCSenhaN.setBackground(new java.awt.Color(204, 204, 230));
        txtCSenhaN.setForeground(new java.awt.Color(66, 33, 99));
        txtCSenhaN.setToolTipText("Confirme a senha do cliente");

        lblGeneroN.setForeground(new java.awt.Color(66, 33, 99));
        lblGeneroN.setText("Gênero:");

        lblNomeN.setForeground(new java.awt.Color(66, 33, 99));
        lblNomeN.setText("Nome:");

        txtNomeN.setBackground(new java.awt.Color(204, 204, 230));
        txtNomeN.setForeground(new java.awt.Color(66, 33, 99));
        txtNomeN.setToolTipText("Digite o nome do cliente");

        lblCpfN.setForeground(new java.awt.Color(66, 33, 99));
        lblCpfN.setText("CPF:");

        txtCpfN.setBackground(new java.awt.Color(204, 204, 230));
        txtCpfN.setForeground(new java.awt.Color(66, 33, 99));
        txtCpfN.setToolTipText("Digite o CPF do cliente");

        lblTelefoneN.setForeground(new java.awt.Color(66, 33, 99));
        lblTelefoneN.setText("Telefone:");

        txtTelefoneN.setBackground(new java.awt.Color(204, 204, 230));
        txtTelefoneN.setForeground(new java.awt.Color(66, 33, 99));
        txtTelefoneN.setToolTipText("Digite o telefone do cliente");
        txtTelefoneN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneNActionPerformed(evt);
            }
        });

        lblEmailN.setForeground(new java.awt.Color(66, 33, 99));
        lblEmailN.setText("Email:");

        cbbGeneroN.setBackground(new java.awt.Color(217, 220, 235));
        cbbGeneroN.setForeground(new java.awt.Color(66, 33, 99));
        cbbGeneroN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outro" }));
        cbbGeneroN.setBorder(null);
        cbbGeneroN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGeneroNActionPerformed(evt);
            }
        });

        lblErroN.setForeground(new java.awt.Color(204, 0, 0));
        lblErroN.setText("Preencha todos os campos");
        lblErroN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnVoltarN.setBackground(new java.awt.Color(204, 204, 230));
        btnVoltarN.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar16.png"))); // NOI18N
        btnVoltarN.setText("Voltar");
        btnVoltarN.setToolTipText("Voltar");
        btnVoltarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarNActionPerformed(evt);
            }
        });

        btnConfirmarN.setBackground(new java.awt.Color(204, 204, 230));
        btnConfirmarN.setForeground(new java.awt.Color(66, 33, 99));
        btnConfirmarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16.png"))); // NOI18N
        btnConfirmarN.setText("Confirmar");
        btnConfirmarN.setToolTipText("Confirmar");
        btnConfirmarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNovaContaLayout = new javax.swing.GroupLayout(pnlNovaConta);
        pnlNovaConta.setLayout(pnlNovaContaLayout);
        pnlNovaContaLayout.setHorizontalGroup(
            pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNovaContaLayout.createSequentialGroup()
                        .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNovaContaLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmailN)
                                    .addComponent(lblTelefoneN)
                                    .addComponent(lblCpfN)
                                    .addComponent(lblNomeN)
                                    .addComponent(lblGeneroN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailN, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCpfN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelefoneN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomeN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbGeneroN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlNovaContaLayout.createSequentialGroup()
                                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDepositoN)
                                    .addComponent(lblCSenhaN)
                                    .addComponent(lblSenhaN)
                                    .addComponent(lblCategoriaN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDepositoN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbCategoriaN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSenhaN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCSenhaN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNovaContaLayout.createSequentialGroup()
                        .addComponent(btnVoltarN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmarN)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNovaContaLayout.createSequentialGroup()
                        .addComponent(lblErroN, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlNovaContaLayout.setVerticalGroup(
            pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovaContaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeN)
                    .addComponent(txtNomeN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfN)
                    .addComponent(txtCpfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneN)
                    .addComponent(txtTelefoneN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailN)
                    .addComponent(txtEmailN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneroN)
                    .addComponent(cbbGeneroN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaN)
                    .addComponent(txtSenhaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCSenhaN)
                    .addComponent(txtCSenhaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepositoN)
                    .addComponent(txtDepositoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaN)
                    .addComponent(cbbCategoriaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErroN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltarN)
                    .addComponent(btnConfirmarN))
                .addContainerGap())
        );

        pnlLogin.setBackground(new java.awt.Color(217, 220, 235));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(66, 33, 99))); // NOI18N
        pnlLogin.setForeground(new java.awt.Color(217, 220, 235));

        lblCpfL.setBackground(new java.awt.Color(204, 204, 230));
        lblCpfL.setForeground(new java.awt.Color(66, 33, 99));
        lblCpfL.setText("CPF:");

        lblSenhaL.setBackground(new java.awt.Color(204, 204, 230));
        lblSenhaL.setForeground(new java.awt.Color(66, 33, 99));
        lblSenhaL.setText("Senha:");

        txtSenhaL.setBackground(new java.awt.Color(204, 204, 230));
        txtSenhaL.setForeground(new java.awt.Color(66, 33, 99));
        txtSenhaL.setToolTipText("Digite sua senha");

        txtCpfL.setBackground(new java.awt.Color(204, 204, 230));
        txtCpfL.setForeground(new java.awt.Color(66, 33, 99));
        txtCpfL.setToolTipText("Digite seu CPF");
        txtCpfL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfLActionPerformed(evt);
            }
        });

        lblErroL.setForeground(new java.awt.Color(204, 0, 0));
        lblErroL.setText("Senha ou CPF incorreto");

        btnVoltarL.setBackground(new java.awt.Color(204, 204, 230));
        btnVoltarL.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar16.png"))); // NOI18N
        btnVoltarL.setText("Voltar");
        btnVoltarL.setToolTipText("Voltar");
        btnVoltarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLActionPerformed(evt);
            }
        });

        btnLoginL.setBackground(new java.awt.Color(204, 204, 230));
        btnLoginL.setForeground(new java.awt.Color(66, 33, 99));
        btnLoginL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16.png"))); // NOI18N
        btnLoginL.setText("Login");
        btnLoginL.setToolTipText("Fazer login");
        btnLoginL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblCpfL))
                    .addComponent(lblSenhaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenhaL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErroL)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnVoltarL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaL)
                    .addComponent(txtSenhaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErroL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarL)
                    .addComponent(btnLoginL))
                .addGap(209, 209, 209))
        );

        pnlTitulo.setBackground(new java.awt.Color(217, 220, 235));
        pnlTitulo.setForeground(new java.awt.Color(217, 220, 235));

        lblTitulo.setFont(new java.awt.Font("Segoe Print", 1, 50)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(66, 33, 99));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("4 Seasoning");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloLayout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(245, 245, 245)))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(lblTitulo)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlPrincipal.setBackground(new java.awt.Color(217, 220, 235));
        pnlPrincipal.setForeground(new java.awt.Color(217, 220, 235));

        btnNovaConta.setBackground(new java.awt.Color(204, 204, 230));
        btnNovaConta.setForeground(new java.awt.Color(66, 33, 99));
        btnNovaConta.setText("Inscrever-se");
        btnNovaConta.setToolTipText("Criar Conta");
        btnNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaContaActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(204, 204, 230));
        btnLogin.setForeground(new java.awt.Color(66, 33, 99));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Fazer Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(691, Short.MAX_VALUE)
                .addComponent(btnNovaConta)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(81, 81, 81))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnNovaConta))
                .addGap(486, 486, 486))
        );

        pnlConta.setBackground(new java.awt.Color(217, 220, 235));
        pnlConta.setForeground(new java.awt.Color(217, 220, 235));

        lblSaldo.setForeground(new java.awt.Color(66, 33, 99));

        btnSaldo.setBackground(new java.awt.Color(204, 204, 230));
        btnSaldo.setForeground(new java.awt.Color(204, 204, 230));
        btnSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho16.png"))); // NOI18N
        btnSaldo.setMnemonic('v');
        btnSaldo.setToolTipText("Visualizar saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnConfig.setBackground(new java.awt.Color(204, 204, 230));
        btnConfig.setForeground(new java.awt.Color(204, 204, 230));
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/config16.png"))); // NOI18N
        btnConfig.setToolTipText("Configurações da conta");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        btnDepositar.setBackground(new java.awt.Color(204, 204, 230));
        btnDepositar.setForeground(new java.awt.Color(204, 204, 230));
        btnDepositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deposito16.png"))); // NOI18N
        btnDepositar.setToolTipText("Fazer depósito");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnPedido.setBackground(new java.awt.Color(204, 204, 230));
        btnPedido.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(66, 33, 99));
        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/prato32.png"))); // NOI18N
        btnPedido.setText("Pedido");
        btnPedido.setToolTipText("Fazer pedido");
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        txtDeposito.setBackground(new java.awt.Color(204, 204, 230));
        txtDeposito.setForeground(new java.awt.Color(66, 33, 99));
        txtDeposito.setToolTipText("Digite o valor de depósito");
        txtDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositoActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 204, 230));
        btnSair.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(66, 33, 99));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair32.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Fechar programa");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConfirmarD.setBackground(new java.awt.Color(204, 204, 230));
        btnConfirmarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16.png"))); // NOI18N
        btnConfirmarD.setToolTipText("Confirmar");
        btnConfirmarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarDActionPerformed(evt);
            }
        });

        lblPagar.setBackground(new java.awt.Color(204, 204, 230));
        lblPagar.setForeground(new java.awt.Color(66, 33, 99));

        btnPagar.setBackground(new java.awt.Color(204, 204, 230));
        btnPagar.setForeground(new java.awt.Color(66, 33, 99));
        btnPagar.setText("Pagar");
        btnPagar.setToolTipText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        lblPago.setBackground(new java.awt.Color(204, 204, 230));
        lblPago.setForeground(new java.awt.Color(66, 33, 99));

        btnVerFatura.setBackground(new java.awt.Color(204, 204, 230));
        btnVerFatura.setForeground(new java.awt.Color(204, 204, 230));
        btnVerFatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fatura16.png"))); // NOI18N
        btnVerFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContaLayout = new javax.swing.GroupLayout(pnlConta);
        pnlConta.setLayout(pnlContaLayout);
        pnlContaLayout.setHorizontalGroup(
            pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContaLayout.createSequentialGroup()
                        .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlContaLayout.createSequentialGroup()
                                .addComponent(btnDepositar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDeposito))
                            .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaldo))
                        .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirmarD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvisoD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVerFatura)
                                    .addGroup(pnlContaLayout.createSequentialGroup()
                                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41))))
                    .addGroup(pnlContaLayout.createSequentialGroup()
                        .addComponent(btnConfig)
                        .addGap(874, 874, 874))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContaLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedido)
                .addGap(370, 370, 370))
        );
        pnlContaLayout.setVerticalGroup(
            pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContaLayout.createSequentialGroup()
                .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnConfig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaldo)
                        .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlContaLayout.createSequentialGroup()
                                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDepositar))
                                    .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnConfirmarD))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContaLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblAvisoD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlContaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnVerFatura)
                        .addGap(18, 18, 18)
                        .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPagar)
                            .addComponent(lblPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedido)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConfig.setBackground(new java.awt.Color(217, 220, 235));
        pnlConfig.setForeground(new java.awt.Color(217, 220, 235));

        lblNome.setForeground(new java.awt.Color(66, 33, 99));
        lblNome.setText("Nome:");

        lblCpf.setForeground(new java.awt.Color(66, 33, 99));
        lblCpf.setText("CPF:");

        lblEmail.setForeground(new java.awt.Color(66, 33, 99));
        lblEmail.setText("Email:");

        lblTelefone.setForeground(new java.awt.Color(66, 33, 99));
        lblTelefone.setText("Telefone:");

        lblGenero.setForeground(new java.awt.Color(66, 33, 99));
        lblGenero.setText("Gênero:");

        lblCategoria.setForeground(new java.awt.Color(66, 33, 99));
        lblCategoria.setText("Categoria:");

        txtNome.setBackground(new java.awt.Color(204, 204, 230));
        txtNome.setForeground(new java.awt.Color(66, 33, 99));
        txtNome.setToolTipText("Seu Nome");

        txtCpf.setBackground(new java.awt.Color(204, 204, 230));
        txtCpf.setForeground(new java.awt.Color(66, 33, 99));
        txtCpf.setToolTipText("Seu CPF");

        txtEmail.setBackground(new java.awt.Color(204, 204, 230));
        txtEmail.setForeground(new java.awt.Color(66, 33, 99));
        txtEmail.setToolTipText("Seu  Email");

        txtTelefone.setBackground(new java.awt.Color(204, 204, 230));
        txtTelefone.setForeground(new java.awt.Color(66, 33, 99));
        txtTelefone.setToolTipText("Seu Telefone");

        cbbGenero.setBackground(new java.awt.Color(204, 204, 230));
        cbbGenero.setForeground(new java.awt.Color(66, 33, 99));
        cbbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        cbbCategoria.setBackground(new java.awt.Color(204, 204, 230));
        cbbCategoria.setForeground(new java.awt.Color(66, 33, 99));
        cbbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic", "Standard", "Premium" }));

        btnExcluir.setBackground(new java.awt.Color(204, 204, 230));
        btnExcluir.setForeground(new java.awt.Color(66, 33, 99));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar16.png"))); // NOI18N
        btnExcluir.setText("Excluir conta");
        btnExcluir.setToolTipText("Excluir conta");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnRestaurar.setBackground(new java.awt.Color(204, 204, 230));
        btnRestaurar.setForeground(new java.awt.Color(66, 33, 99));
        btnRestaurar.setText("Restaurar");
        btnRestaurar.setToolTipText("Desfazer mudanças");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(204, 204, 230));
        btnSalvar.setForeground(new java.awt.Color(66, 33, 99));
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar mudanças");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfigLayout = new javax.swing.GroupLayout(pnlConfig);
        pnlConfig.setLayout(pnlConfigLayout);
        pnlConfigLayout.setHorizontalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConfigLayout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(323, 323, 323)
                        .addComponent(btnRestaurar))
                    .addGroup(pnlConfigLayout.createSequentialGroup()
                        .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblCpf)
                            .addComponent(lblEmail)
                            .addComponent(lblTelefone)
                            .addComponent(lblGenero)
                            .addComponent(lblCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConfigLayout.setVerticalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(cbbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria)
                        .addComponent(cbbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnRestaurar)
                    .addComponent(btnSalvar))
                .addGap(111, 111, 111))
        );

        lpnConta.setLayer(pnlConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnConta.setLayer(pnlConfig, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnContaLayout = new javax.swing.GroupLayout(lpnConta);
        lpnConta.setLayout(lpnContaLayout);
        lpnContaLayout.setHorizontalGroup(
            lpnContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpnContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lpnContaLayout.setVerticalGroup(
            lpnContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnContaLayout.createSequentialGroup()
                .addComponent(pnlConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lpnPrincipal.setLayer(pnlNovaConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(pnlLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(pnlTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(pnlPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(lpnConta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnPrincipalLayout = new javax.swing.GroupLayout(lpnPrincipal);
        lpnPrincipal.setLayout(lpnPrincipalLayout);
        lpnPrincipalLayout.setHorizontalGroup(
            lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(pnlNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lpnConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        lpnPrincipalLayout.setVerticalGroup(
            lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnPrincipalLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(pnlNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(lpnConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(976, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        pnlLogin.setVisible(true);
        pnlPrincipal.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaContaActionPerformed
        pnlNovaConta.setVisible(true);
        pnlPrincipal.setVisible(false);
    }//GEN-LAST:event_btnNovaContaActionPerformed

    private void txtTelefoneNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneNActionPerformed

    private void cbbGeneroNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGeneroNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGeneroNActionPerformed

    private void txtCpfLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfLActionPerformed

    private void btnVoltarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarNActionPerformed
        pnlNovaConta.setVisible(false);
        pnlPrincipal.setVisible(true);
        txtNomeN.setText("");
        txtCpfN.setText("");
        txtTelefoneN.setText("");
        txtEmailN.setText("");
        txtSenhaN.setText("");
        txtCSenhaN.setText("");
        txtDepositoN.setText("");
        cbbGeneroN.setSelectedIndex(0);
        cbbCategoriaN.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltarNActionPerformed
    /**
     * metodo para registrar uma nova conta
     * @param evt 
     */
    private void btnConfirmarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarNActionPerformed
        String senha = new String(txtSenhaN.getPassword());
        String confirmarSenha = new String(txtCSenhaN.getPassword());
    
        if(txtNomeN.getText().equals("") || txtCpfN.getText().equals("") ||
            txtTelefoneN.getText().equals("") || txtEmailN.getText().equals("") ||
            senha.equals("") || confirmarSenha.equals("") || txtDepositoN.getText().equals("") ||
            cbbCategoriaN.getSelectedIndex() == 0 || cbbGeneroN.getSelectedIndex() == 0){
            
            lblErroN.setText("Preencha todos campos");    
            lblErroN.setForeground(Color.red);
            lblErroN.setVisible(true);
                
        }else if(!senha.equals(confirmarSenha)){
            lblErroN.setText("Senhas não correspondem");    
            lblErroN.setForeground(Color.red);
            lblErroN.setVisible(true);
            
        }else if(cbbCategoriaN.getSelectedIndex() == 2 && Double.parseDouble(txtDepositoN.getText()) < 119.9){
            lblErroN.setVisible(true);
            lblErroN.setText("Depósito insuficiente. Depósito mínimo R$119.90");
            
        }else if(cbbCategoriaN.getSelectedIndex() == 3 && Double.parseDouble(txtDepositoN.getText()) < 199.9){
            lblErroN.setVisible(true);
            lblErroN.setText("Depósito insuficiente. Depósito mínimo R$199.90");
            
        }else if(gerente.pesquisarConta(txtCpfN.getText()) != null){
            lblErroN.setVisible(true);
            lblErroN.setText("Conta já existente");
            
        }
        else{
            Conta novaConta = new Conta();
            novaConta.setNome(txtNomeN.getText());
            novaConta.setCpf(txtCpfN.getText());
            novaConta.setTelefone(txtTelefoneN.getText());
            novaConta.setEmail(txtEmailN.getText());
            novaConta.setSenha(senha);
            novaConta.setSaldo(Double.parseDouble(txtDepositoN.getText()));
            novaConta.setCategoria(cbbCategoriaN.getSelectedItem().toString());
            novaConta.setGenero(cbbGeneroN.getSelectedItem().toString().toLowerCase().charAt(0));
            novaConta.setIdConta(getContas().get(getContas().size()-1).getIdConta() + 1);
            novaConta.setPago(true);
            // definindo a mesa da nova conta
            novaConta.setMesa(new Mesa((byte)0));
            gerente.addConta(novaConta);
            conta = novaConta;
            
            if(!conta.isPago()){
                    btnPedido.setEnabled(false);
                    btnPedido.setToolTipText("Pague a fatura");
            }else{
                    btnPedido.setEnabled(true);
                    btnPedido.setToolTipText("Fazer pedido");
            }
            
            pnlNovaConta.setVisible(false);
            lpnConta.setVisible(true);
            pnlConta.setVisible(true);
            
            lblTitulo.setText("Olá, " + conta.getNome().split(" ")[0]);
        }
    }//GEN-LAST:event_btnConfirmarNActionPerformed

    private void btnVoltarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLActionPerformed
        pnlLogin.setVisible(false);
        pnlPrincipal.setVisible(true);
        txtCpfL.setText("");
        txtSenhaL.setText("");
    }//GEN-LAST:event_btnVoltarLActionPerformed
    /**
     * metodo que faz o login na conta apos fazer algumas verificacoes
     * @param evt 
     */
    private void btnLoginLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLActionPerformed
        String senha = new String(txtSenhaL.getPassword());
        String cpf = txtCpfL.getText();
        boolean flag = false;
       
        
        for(Conta c: contas){
            if(c.getCpf().equals(cpf) && c.isSenha(senha)){
                conta = c;
                pnlLogin.setVisible(false);
                lpnConta.setVisible(true);
                pnlConta.setVisible(true);
                flag = true;
                lblTitulo.setText("Olá, " + conta.getNome().split(" ")[0]);
                if(!conta.isPago()){
                    btnPedido.setEnabled(false);
                    btnPedido.setToolTipText("Pague a fatura");
                }else{
                    btnPedido.setEnabled(true);
                    btnPedido.setToolTipText("Fazer pedido");
                }
                
                break;
            }
        }

        if(!conta.isPago()){
            btnPagar.setVisible(true);
            lblPagar.setVisible(true);
            lblPagar.setText("Total a pagar: R$" + String.format("%.2f",conta.getFatura()));
        }else{
            btnPagar.setVisible(false);
            lblPagar.setText("");
        }
        
        if(!flag){
            lblErroL.setVisible(true);
            txtCpfL.setText("");
            txtSenhaL.setText("");
        }
    }//GEN-LAST:event_btnLoginLActionPerformed
    /**
     * metodo que exibe o saldo da conta quando o btnSaldo esta ativado
     * @param evt 
     */
    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        if(btnSaldo.isSelected()){
            lblSaldo.setText("Saldo: R$" + String.format("%.2f", conta.getSaldo()));
            lblSaldo.setVisible(true);
        }else{
            lblSaldo.setText("");
        }
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void txtDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositoActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
       txtDeposito.setVisible(true);
       btnConfirmarD.setVisible(true);
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        gerente.marcarPonto();
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed
    /**
     * metodo que exibe o panel que permite a conta visualizar suas informacoes, 
     * modificar ou excluir a conta
     * @param evt 
     */
    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        pnlConfig.setVisible(true);
        txtNome.setText(conta.getNome());
        txtCpf.setText(conta.getCpf());
        txtCpf.setEditable(false);
        txtEmail.setText(conta.getEmail());
        txtTelefone.setText(conta.getTelefone());
        
        switch (conta.getGenero()) {
            case 'm':
                cbbGenero.setSelectedIndex(0);
                break;
            case 'f':
                cbbGenero.setSelectedIndex(1);
                break;
            default:
                cbbGenero.setSelectedIndex(2);
                break;
        }
        
        switch (conta.getCategoria()){
            case "Basic":
                cbbCategoria.setSelectedIndex(0);
                break;
            case "Standard":
                cbbCategoria.setSelectedIndex(1);
                break;
            case "Premium":
                cbbCategoria.setSelectedIndex(2);
                break;
        }
    }//GEN-LAST:event_btnConfigActionPerformed
    /**
     * metodo para realizar um deposito
     * @param evt 
     */
    private void btnConfirmarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarDActionPerformed
        try{
            conta.depositar(Double.parseDouble(txtDeposito.getText()));
            lblAvisoD.setForeground(new Color(0,120,56));
            lblAvisoD.setText("Depósito realizado com sucesso");
            txtDeposito.setText("");
        }catch(Exception e){
            lblAvisoD.setForeground(Color.red);
            lblAvisoD.setText("Valor inválido");
            txtDeposito.setText("");
        }
    }//GEN-LAST:event_btnConfirmarDActionPerformed
    /**
     * metodo onde a conta pode ser excluida
     * @param evt 
     */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String senha = JOptionPane.showInputDialog(null, "Digite sua senha", "Tem certeza?", JOptionPane.QUESTION_MESSAGE);
        if(conta.isSenha(senha)){
            gerente.rmConta(conta);
            JOptionPane.showMessageDialog(null, "Conta removida", "Aviso", JOptionPane.WARNING_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Senha incorreta", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    /**
     * a conta pode modificar seus dados e nesse botao ele salva as alteracoes
     * @param evt 
     */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        conta.setNome(txtNome.getText());
        conta.setEmail(txtEmail.getText());
        conta.setTelefone(txtTelefone.getText());
        conta.setCategoria(cbbCategoria.getSelectedItem().toString());
        switch(cbbGenero.getSelectedItem().toString()){
            case "Masculino":
                conta.setGenero('m');
                break;
            case "Feminino":
                conta.setGenero('f');
                break;
            case "Outro":
                conta.setGenero('o');
                break;
        }
        lblInfo.setForeground(new Color(0,120,56));
        lblInfo.setText("Dados atualizados");
    }//GEN-LAST:event_btnSalvarActionPerformed
    /**
     * metodo para restaurar os dados da conta
     * @param evt 
     */
    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        txtNome.setText(conta.getNome());
        txtCpf.setText(conta.getCpf());
        txtCpf.setEditable(false);
        txtEmail.setText(conta.getEmail());
        txtTelefone.setText(conta.getTelefone());
        
        switch (conta.getGenero()) {
            case 'm':
                cbbGenero.setSelectedIndex(0);
                break;
            case 'f':
                cbbGenero.setSelectedIndex(1);
                break;
            default:
                cbbGenero.setSelectedIndex(2);
                break;
        }
        
        switch (conta.getCategoria()){
            case "Basic":
                cbbCategoria.setSelectedIndex(0);
                break;
            case "Standard":
                cbbCategoria.setSelectedIndex(1);
                break;
            case "Premium":
                cbbCategoria.setSelectedIndex(2);
                break;
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed
    /**
     * metodo onde se inicia o pedido, esse botao vai exibir a tela de selecao de mesa
     * @param evt 
     */
    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        if(conta.getMesa().getNum() == 0){
            pedido.setConta(conta);        
            lblPagar.setVisible(false);
            lblAvisoD.setVisible(false);
            new TelaMesa().setVisible(true);
        }else{
            tela.setVisible(true);
        }
    }//GEN-LAST:event_btnPedidoActionPerformed
    /**
     * metodo para a conta pagar a fatura pendente
     * @param evt 
     */
    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        
        if(conta.pagar()){
            lblPago.setForeground(new Color(0,120,56));
            lblPago.setText("Fatura paga com sucesso!");
            lblPagar.setText("");
            gerente.marcarPonto();
            btnPedido.setEnabled(true);
            
        }else{
            lblPago.setForeground(Color.red);
            lblPago.setText("Saldo insuficiente, faça um depósito");
        }
    }//GEN-LAST:event_btnPagarActionPerformed
    /**
     * metodo que da funcao ao btnVerFatura, faz uma verificacao simples para ver
     * se a conta tem alguma fatura pendente
     * @param evt 
     */
    private void btnVerFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFaturaActionPerformed
        if(!conta.isPago()){
            btnPagar.setVisible(true);
            lblPagar.setVisible(true);
            lblPagar.setText("Total a pagar: R$" + String.format("%.2f",conta.getFatura()));

        }else{
            btnPagar.setVisible(false);
            lblPagar.setText("Você não tem fatura pendente");
            lblPagar.setVisible(true);

        }
    }//GEN-LAST:event_btnVerFaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnConfirmarD;
    private javax.swing.JButton btnConfirmarN;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginL;
    private javax.swing.JButton btnNovaConta;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSair;
    private javax.swing.JToggleButton btnSaldo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVerFatura;
    private javax.swing.JButton btnVoltarL;
    private javax.swing.JButton btnVoltarN;
    private javax.swing.JComboBox<String> cbbCategoria;
    private javax.swing.JComboBox<String> cbbCategoriaN;
    private javax.swing.JComboBox<String> cbbGenero;
    private javax.swing.JComboBox<String> cbbGeneroN;
    private javax.swing.JLabel lblAvisoD;
    private javax.swing.JLabel lblCSenhaN;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoriaN;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpfL;
    private javax.swing.JLabel lblCpfN;
    private javax.swing.JLabel lblDepositoN;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailN;
    private javax.swing.JLabel lblErroL;
    private javax.swing.JLabel lblErroN;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGeneroN;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeN;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSenhaL;
    private javax.swing.JLabel lblSenhaN;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefoneN;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLayeredPane lpnConta;
    private javax.swing.JLayeredPane lpnPrincipal;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlConta;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlNovaConta;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPasswordField txtCSenhaN;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCpfL;
    private javax.swing.JTextField txtCpfN;
    private javax.swing.JTextField txtDeposito;
    private javax.swing.JTextField txtDepositoN;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailN;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeN;
    private javax.swing.JPasswordField txtSenhaL;
    private javax.swing.JPasswordField txtSenhaN;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneN;
    // End of variables declaration//GEN-END:variables
}
