/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import fourseasoning.Prato;
import static fourseasoning.Funcionario.getPratos;
import fourseasoning.ItemPedido;
import fourseasoning.Pedido;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static telas.TelaConta.conta;
import static telas.TelaConta.pedido;

public class TelaPrato extends javax.swing.JFrame {
    ArrayList<Prato> pratos = getPratos();
    ArrayList<Prato> verao = new ArrayList<>();
    ArrayList<Prato> outono = new ArrayList<>();
    ArrayList<Prato> inverno = new ArrayList<>();
    ArrayList<Prato> primavera = new ArrayList<>();

    
    public TelaPrato() {
        initComponents();
        // Troca a cor do JFrame
        Color cor = new Color(217,220,235);
        getContentPane().setBackground(cor);       
        
        /**
         * Construimos os Arrays para cada estacao. Isso eh necessario, pois cada 
         * estacao tem uma tela diferente
         */
        for(Prato p: pratos){
            if(p.getEstacao().equals("verao")){
                verao.add(p);
            }else if(p.getEstacao().equals("outono")){
                outono.add(p);
            }else if(p.getEstacao().equals("inverno")){
                inverno.add(p);
            }else{
                primavera.add(p);
            }
        }
        
        
        LocalDate hoje = LocalDate.now();
        int dia = hoje.getDayOfMonth();
        int mes = hoje.getMonthValue();
        defineEstacao(dia, mes);
    /***************************************************************************
     * Esse bloco foi usado para testes 
     *       
     *   LocalDate verao = LocalDate.of(2022,2,27);
     *   LocalDate outono = LocalDate.of(2022,5,27);
     *   LocalDate inverno = LocalDate.of(2022,8,27);
     *   LocalDate primavera = LocalDate.of(2022,11,27);
     *   int diaV = verao.getDayOfMonth();
     *   int mesV = verao.getMonthValue();
     *   int diaO = outono.getDayOfMonth();
     *   int mesO = outono.getMonthValue();
     *   int diaI = inverno.getDayOfMonth();
     *   int mesI = inverno.getMonthValue();
     *   int diaP = primavera.getDayOfMonth();
     *   int mesP = primavera.getMonthValue();
     *   defineEstacao(diaV, mesV);
     *   //defineEstacao(diaO, mesO);
     *   //defineEstacao(diaI, mesI);
     *   //defineEstacao(diaP, mesP);
     **************************************************************************/  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnPrincipal = new javax.swing.JLayeredPane();
        pnlVerao = new javax.swing.JPanel();
        pnlVerao.setVisible(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerao = new javax.swing.JTable();
        btnVisualizarV = new javax.swing.JButton();
        btnVisualizarV.setEnabled(false);
        btnAddV = new javax.swing.JButton();
        btnVoltarV = new javax.swing.JButton();
        pnlTituloV = new javax.swing.JPanel();
        lblTituloV = new javax.swing.JLabel();
        txtDescricaoV = new javax.swing.JTextArea();
        txtDescricaoV.setEditable(false);
        txtQtdV = new javax.swing.JTextField();
        lblTamanhoV = new javax.swing.JLabel();
        lblQtdV = new javax.swing.JLabel();
        cbbTamanhoV = new javax.swing.JComboBox<>();
        lblSubtotalV = new javax.swing.JLabel();
        lblErroQtdV = new javax.swing.JLabel();
        lblErroTamV = new javax.swing.JLabel();
        pnlOutono = new javax.swing.JPanel();
        pnlOutono.setVisible(false);
        jScrollPane5 = new javax.swing.JScrollPane();
        tblOutono = new javax.swing.JTable();
        pnlTituloO = new javax.swing.JPanel();
        lblTituloO = new javax.swing.JLabel();
        txtDescricaoO = new javax.swing.JTextArea();
        btnVoltarO = new javax.swing.JButton();
        btnVisualizarO = new javax.swing.JButton();
        btnVisualizarO.setEnabled(false);
        btnAddO = new javax.swing.JButton();
        txtQtdO = new javax.swing.JTextField();
        lblTamanhoO = new javax.swing.JLabel();
        lblQtdO = new javax.swing.JLabel();
        cbbTamanhoO = new javax.swing.JComboBox<>();
        lblSubtotalO = new javax.swing.JLabel();
        lblErroTamO = new javax.swing.JLabel();
        lblErroQtdO = new javax.swing.JLabel();
        pnlInverno = new javax.swing.JPanel();
        pnlInverno.setVisible(false);
        jScrollPane6 = new javax.swing.JScrollPane();
        tblInverno = new javax.swing.JTable();
        btnVisualizarI = new javax.swing.JButton();
        btnVisualizarI.setEnabled(false);
        btnAddI = new javax.swing.JButton();
        btnVoltarI = new javax.swing.JButton();
        txtDescricaoI = new javax.swing.JTextArea();
        pnlTituloI = new javax.swing.JPanel();
        lblTituloI = new javax.swing.JLabel();
        lblTamanhoI = new javax.swing.JLabel();
        lblQtdI = new javax.swing.JLabel();
        cbbTamanhoI = new javax.swing.JComboBox<>();
        txtQtdI = new javax.swing.JTextField();
        lblSubtotalI = new javax.swing.JLabel();
        lblErroQtdI = new javax.swing.JLabel();
        lblErroTamI = new javax.swing.JLabel();
        pnlPrimavera = new javax.swing.JPanel();
        pnlPrimavera.setVisible(false);
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPrimavera = new javax.swing.JTable();
        pnlTituloP = new javax.swing.JPanel();
        lblTituloP = new javax.swing.JLabel();
        txtDescricaoP = new javax.swing.JTextArea();
        btnVoltarP = new javax.swing.JButton();
        btnVisualizarP = new javax.swing.JButton();
        btnVisualizarP.setEnabled(false);
        btnAddP = new javax.swing.JButton();
        lblTamanhoP = new javax.swing.JLabel();
        lblQtdP = new javax.swing.JLabel();
        cbbTamanhoP = new javax.swing.JComboBox<>();
        txtQtdP = new javax.swing.JTextField();
        lblSubtotalP = new javax.swing.JLabel();
        lblErroQtdP = new javax.swing.JLabel();
        lblErroTamP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cardápio");

        lpnPrincipal.setBackground(new java.awt.Color(217, 220, 235));
        lpnPrincipal.setForeground(new java.awt.Color(217, 220, 235));
        lpnPrincipal.setPreferredSize(new java.awt.Dimension(936, 616));

        pnlVerao.setBackground(new java.awt.Color(255, 204, 153));
        pnlVerao.setForeground(new java.awt.Color(255, 204, 153));
        pnlVerao.setPreferredSize(new java.awt.Dimension(936, 616));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 153));
        jScrollPane1.setForeground(new java.awt.Color(255, 204, 153));
        jScrollPane1.setToolTipText("Escolha um prato");
        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        tblVerao.setBackground(new java.awt.Color(255, 204, 153));
        tblVerao.setForeground(new java.awt.Color(66, 33, 99));
        tblVerao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Prato", "Preço", "Tempo de Preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVerao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeraoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVerao);
        if (tblVerao.getColumnModel().getColumnCount() > 0) {
            tblVerao.getColumnModel().getColumn(0).setResizable(false);
            tblVerao.getColumnModel().getColumn(1).setResizable(false);
            tblVerao.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVisualizarV.setBackground(new java.awt.Color(255, 188, 143));
        btnVisualizarV.setForeground(new java.awt.Color(66, 33, 99));
        btnVisualizarV.setText("Visualizar");
        btnVisualizarV.setToolTipText("Visualizar Pedido");
        btnVisualizarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarVActionPerformed(evt);
            }
        });

        btnAddV.setBackground(new java.awt.Color(255, 188, 143));
        btnAddV.setForeground(new java.awt.Color(66, 33, 99));
        btnAddV.setText("Adicionar");
        btnAddV.setToolTipText("Adicionar prato ao pedido");
        btnAddV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVActionPerformed(evt);
            }
        });

        btnVoltarV.setBackground(new java.awt.Color(255, 188, 143));
        btnVoltarV.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltarV.setText("Voltar");
        btnVoltarV.setToolTipText("Voltar");
        btnVoltarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarVActionPerformed(evt);
            }
        });

        pnlTituloV.setBackground(new java.awt.Color(255, 204, 153));

        lblTituloV.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lblTituloV.setForeground(new java.awt.Color(66, 33, 99));
        lblTituloV.setText("Cardápio de verão");

        javax.swing.GroupLayout pnlTituloVLayout = new javax.swing.GroupLayout(pnlTituloV);
        pnlTituloV.setLayout(pnlTituloVLayout);
        pnlTituloVLayout.setHorizontalGroup(
            pnlTituloVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloVLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(lblTituloV)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        pnlTituloVLayout.setVerticalGroup(
            pnlTituloVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloV, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        txtDescricaoV.setBackground(new java.awt.Color(255, 204, 153));
        txtDescricaoV.setColumns(20);
        txtDescricaoV.setForeground(new java.awt.Color(66, 33, 99));
        txtDescricaoV.setRows(2);

        txtQtdV.setBackground(new java.awt.Color(255, 188, 143));
        txtQtdV.setForeground(new java.awt.Color(66, 33, 99));
        txtQtdV.setText("1");
        txtQtdV.setToolTipText("Digite a quantidade de pratos");

        lblTamanhoV.setForeground(new java.awt.Color(66, 33, 99));
        lblTamanhoV.setText("Tamanho:");

        lblQtdV.setForeground(new java.awt.Color(66, 33, 99));
        lblQtdV.setText("Quantidade:");

        cbbTamanhoV.setBackground(new java.awt.Color(255, 188, 143));
        cbbTamanhoV.setForeground(new java.awt.Color(66, 33, 99));
        cbbTamanhoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tamanho", "Pequeno", "Médio", "Grande" }));
        cbbTamanhoV.setToolTipText("Selecione o tamanho do prato");

        lblSubtotalV.setForeground(new java.awt.Color(66, 33, 99));

        lblErroQtdV.setForeground(new java.awt.Color(204, 0, 0));

        lblErroTamV.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlVeraoLayout = new javax.swing.GroupLayout(pnlVerao);
        pnlVerao.setLayout(pnlVeraoLayout);
        pnlVeraoLayout.setHorizontalGroup(
            pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlTituloV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVeraoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDescricaoV)
                .addContainerGap())
            .addGroup(pnlVeraoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtdV)
                    .addComponent(lblTamanhoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVeraoLayout.createSequentialGroup()
                        .addComponent(cbbTamanhoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErroTamV, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVeraoLayout.createSequentialGroup()
                        .addComponent(txtQtdV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErroQtdV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubtotalV, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(pnlVeraoLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnVoltarV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVeraoLayout.setVerticalGroup(
            pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVeraoLayout.createSequentialGroup()
                .addComponent(pnlTituloV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricaoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTamanhoV)
                        .addComponent(cbbTamanhoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSubtotalV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErroTamV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVeraoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblQtdV)
                                .addComponent(txtQtdV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblErroQtdV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVeraoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlVeraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltarV)
                            .addComponent(btnAddV)
                            .addComponent(btnVisualizarV))
                        .addGap(65, 65, 65))))
        );

        pnlOutono.setBackground(new java.awt.Color(255, 255, 180));
        pnlOutono.setForeground(new java.awt.Color(227, 229, 126));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 180));
        jScrollPane5.setForeground(new java.awt.Color(255, 255, 180));

        tblOutono.setBackground(new java.awt.Color(255, 255, 180));
        tblOutono.setForeground(new java.awt.Color(66, 33, 99));
        tblOutono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Prato", "Preço", "Tempo de Preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOutono.setSelectionBackground(new java.awt.Color(66, 33, 99));
        tblOutono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOutonoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblOutono);
        if (tblOutono.getColumnModel().getColumnCount() > 0) {
            tblOutono.getColumnModel().getColumn(0).setResizable(false);
            tblOutono.getColumnModel().getColumn(1).setResizable(false);
            tblOutono.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlTituloO.setBackground(new java.awt.Color(255, 255, 180));

        lblTituloO.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lblTituloO.setForeground(new java.awt.Color(66, 33, 99));
        lblTituloO.setText("Cardápio de outono");

        javax.swing.GroupLayout pnlTituloOLayout = new javax.swing.GroupLayout(pnlTituloO);
        pnlTituloO.setLayout(pnlTituloOLayout);
        pnlTituloOLayout.setHorizontalGroup(
            pnlTituloOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloO)
                .addGap(229, 229, 229))
        );
        pnlTituloOLayout.setVerticalGroup(
            pnlTituloOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloO, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDescricaoO.setBackground(new java.awt.Color(255, 255, 180));
        txtDescricaoO.setColumns(20);
        txtDescricaoO.setForeground(new java.awt.Color(66, 33, 99));
        txtDescricaoO.setRows(2);

        btnVoltarO.setBackground(new java.awt.Color(227, 229, 126));
        btnVoltarO.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltarO.setText("Voltar");
        btnVoltarO.setToolTipText("Voltar");
        btnVoltarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarOActionPerformed(evt);
            }
        });

        btnVisualizarO.setBackground(new java.awt.Color(227, 229, 126));
        btnVisualizarO.setForeground(new java.awt.Color(66, 33, 99));
        btnVisualizarO.setText("Visualizar");
        btnVisualizarO.setToolTipText("Visualizar Pedido");
        btnVisualizarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarOActionPerformed(evt);
            }
        });

        btnAddO.setBackground(new java.awt.Color(227, 229, 126));
        btnAddO.setForeground(new java.awt.Color(66, 33, 99));
        btnAddO.setText("Adicionar");
        btnAddO.setToolTipText("Adicionar prato ao pedido");
        btnAddO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOActionPerformed(evt);
            }
        });

        txtQtdO.setBackground(new java.awt.Color(227, 229, 126));
        txtQtdO.setForeground(new java.awt.Color(66, 33, 99));
        txtQtdO.setText("1");
        txtQtdO.setToolTipText("Digite a quantidade de pratos");

        lblTamanhoO.setForeground(new java.awt.Color(66, 33, 99));
        lblTamanhoO.setText("Tamanho:");

        lblQtdO.setForeground(new java.awt.Color(66, 33, 99));
        lblQtdO.setText("Quantidade:");

        cbbTamanhoO.setBackground(new java.awt.Color(227, 229, 126));
        cbbTamanhoO.setForeground(new java.awt.Color(66, 33, 99));
        cbbTamanhoO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tamanho", "Pequeno", "Médio", "Grande" }));
        cbbTamanhoO.setToolTipText("Selecione o tamanho do prato");

        lblSubtotalO.setForeground(new java.awt.Color(66, 33, 99));

        lblErroTamO.setForeground(new java.awt.Color(204, 0, 0));

        lblErroQtdO.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlOutonoLayout = new javax.swing.GroupLayout(pnlOutono);
        pnlOutono.setLayout(pnlOutonoLayout);
        pnlOutonoLayout.setHorizontalGroup(
            pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addComponent(pnlTituloO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlOutonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDescricaoO)
                .addContainerGap())
            .addGroup(pnlOutonoLayout.createSequentialGroup()
                .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOutonoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQtdO)
                            .addComponent(lblTamanhoO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOutonoLayout.createSequentialGroup()
                                .addComponent(txtQtdO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErroQtdO, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOutonoLayout.createSequentialGroup()
                                .addComponent(cbbTamanhoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErroTamO, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutonoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltarO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOutonoLayout.createSequentialGroup()
                        .addComponent(btnAddO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizarO)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutonoLayout.createSequentialGroup()
                        .addComponent(lblSubtotalO, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        pnlOutonoLayout.setVerticalGroup(
            pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutonoLayout.createSequentialGroup()
                .addComponent(pnlTituloO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricaoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOutonoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTamanhoO)
                            .addComponent(cbbTamanhoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtotalO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErroTamO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtdO)
                            .addComponent(txtQtdO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErroQtdO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutonoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(pnlOutonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddO)
                            .addComponent(btnVoltarO)
                            .addComponent(btnVisualizarO))
                        .addGap(65, 65, 65))))
        );

        pnlInverno.setBackground(new java.awt.Color(204, 255, 255));
        pnlInverno.setForeground(new java.awt.Color(156, 217, 237));

        jScrollPane6.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane6.setForeground(new java.awt.Color(204, 255, 255));
        jScrollPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseClicked(evt);
            }
        });

        tblInverno.setBackground(new java.awt.Color(204, 255, 255));
        tblInverno.setForeground(new java.awt.Color(66, 33, 99));
        tblInverno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Prato", "Preço", "Tempo de Preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInverno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvernoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblInverno);
        if (tblInverno.getColumnModel().getColumnCount() > 0) {
            tblInverno.getColumnModel().getColumn(0).setResizable(false);
            tblInverno.getColumnModel().getColumn(1).setResizable(false);
            tblInverno.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVisualizarI.setBackground(new java.awt.Color(156, 217, 237));
        btnVisualizarI.setForeground(new java.awt.Color(66, 33, 99));
        btnVisualizarI.setText("Visualizar");
        btnVisualizarI.setToolTipText("Visualizar Pedido");
        btnVisualizarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarIActionPerformed(evt);
            }
        });

        btnAddI.setBackground(new java.awt.Color(156, 217, 237));
        btnAddI.setForeground(new java.awt.Color(66, 33, 99));
        btnAddI.setText("Adicionar");
        btnAddI.setToolTipText("Adicionar prato ao pedido");
        btnAddI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIActionPerformed(evt);
            }
        });

        btnVoltarI.setBackground(new java.awt.Color(156, 217, 237));
        btnVoltarI.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltarI.setText("Voltar");
        btnVoltarI.setToolTipText("Voltar");
        btnVoltarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarIActionPerformed(evt);
            }
        });

        txtDescricaoI.setBackground(new java.awt.Color(204, 255, 255));
        txtDescricaoI.setColumns(20);
        txtDescricaoI.setForeground(new java.awt.Color(66, 33, 99));
        txtDescricaoI.setRows(2);

        pnlTituloI.setBackground(new java.awt.Color(204, 255, 255));
        pnlTituloI.setForeground(new java.awt.Color(204, 255, 255));

        lblTituloI.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lblTituloI.setForeground(new java.awt.Color(66, 33, 99));
        lblTituloI.setText("Cardápio de inverno");

        javax.swing.GroupLayout pnlTituloILayout = new javax.swing.GroupLayout(pnlTituloI);
        pnlTituloI.setLayout(pnlTituloILayout);
        pnlTituloILayout.setHorizontalGroup(
            pnlTituloILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloILayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblTituloI)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        pnlTituloILayout.setVerticalGroup(
            pnlTituloILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloI)
        );

        lblTamanhoI.setForeground(new java.awt.Color(66, 33, 99));
        lblTamanhoI.setText("Tamanho:");

        lblQtdI.setForeground(new java.awt.Color(66, 33, 99));
        lblQtdI.setText("Quantidade:");

        cbbTamanhoI.setBackground(new java.awt.Color(156, 217, 237));
        cbbTamanhoI.setForeground(new java.awt.Color(66, 33, 99));
        cbbTamanhoI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tamanho", "Pequeno", "Médio", "Grande" }));
        cbbTamanhoI.setToolTipText("Selecione o tamanho do prato");

        txtQtdI.setBackground(new java.awt.Color(156, 217, 237));
        txtQtdI.setForeground(new java.awt.Color(66, 33, 99));
        txtQtdI.setText("1");
        txtQtdI.setToolTipText("Digite a quantidade de pratos");

        lblSubtotalI.setForeground(new java.awt.Color(66, 33, 99));

        lblErroQtdI.setForeground(new java.awt.Color(204, 0, 0));

        lblErroTamI.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlInvernoLayout = new javax.swing.GroupLayout(pnlInverno);
        pnlInverno.setLayout(pnlInvernoLayout);
        pnlInvernoLayout.setHorizontalGroup(
            pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addComponent(pnlTituloI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlInvernoLayout.createSequentialGroup()
                .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvernoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDescricaoI))
                    .addGroup(pnlInvernoLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btnVoltarI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddI)
                        .addGap(6, 6, 6)
                        .addComponent(btnVisualizarI)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlInvernoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtdI)
                    .addComponent(lblTamanhoI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvernoLayout.createSequentialGroup()
                        .addComponent(txtQtdI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErroQtdI, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInvernoLayout.createSequentialGroup()
                        .addComponent(cbbTamanhoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErroTamI, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubtotalI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        pnlInvernoLayout.setVerticalGroup(
            pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvernoLayout.createSequentialGroup()
                .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInvernoLayout.createSequentialGroup()
                        .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInvernoLayout.createSequentialGroup()
                                .addComponent(pnlTituloI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTamanhoI)
                                        .addComponent(cbbTamanhoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblErroTamI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblSubtotalI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtdI)
                            .addComponent(txtQtdI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblErroQtdI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInvernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarI)
                    .addComponent(btnAddI)
                    .addComponent(btnVisualizarI))
                .addGap(65, 65, 65))
        );

        pnlPrimavera.setBackground(new java.awt.Color(255, 204, 204));
        pnlPrimavera.setForeground(new java.awt.Color(255, 153, 153));
        pnlPrimavera.setPreferredSize(new java.awt.Dimension(936, 616));

        jScrollPane7.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPane7.setForeground(new java.awt.Color(66, 33, 99));
        jScrollPane7.setToolTipText("Selecione um prato");

        tblPrimavera.setBackground(new java.awt.Color(255, 204, 204));
        tblPrimavera.setForeground(new java.awt.Color(66, 33, 99));
        tblPrimavera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Prato", "Preço", "Tempo de Preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrimavera.setToolTipText("");
        tblPrimavera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrimaveraMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblPrimavera);
        if (tblPrimavera.getColumnModel().getColumnCount() > 0) {
            tblPrimavera.getColumnModel().getColumn(0).setResizable(false);
            tblPrimavera.getColumnModel().getColumn(1).setResizable(false);
            tblPrimavera.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlTituloP.setBackground(new java.awt.Color(255, 204, 204));
        pnlTituloP.setForeground(new java.awt.Color(255, 204, 204));

        lblTituloP.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        lblTituloP.setForeground(new java.awt.Color(66, 33, 99));
        lblTituloP.setText("Cardápio de primavera");

        javax.swing.GroupLayout pnlTituloPLayout = new javax.swing.GroupLayout(pnlTituloP);
        pnlTituloP.setLayout(pnlTituloPLayout);
        pnlTituloPLayout.setHorizontalGroup(
            pnlTituloPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloP)
                .addGap(187, 187, 187))
        );
        pnlTituloPLayout.setVerticalGroup(
            pnlTituloPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloP, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        txtDescricaoP.setBackground(new java.awt.Color(255, 204, 204));
        txtDescricaoP.setColumns(20);
        txtDescricaoP.setForeground(new java.awt.Color(66, 33, 99));
        txtDescricaoP.setRows(2);

        btnVoltarP.setBackground(new java.awt.Color(255, 166, 166));
        btnVoltarP.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltarP.setText("Voltar");
        btnVoltarP.setToolTipText("Voltar");
        btnVoltarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPActionPerformed(evt);
            }
        });

        btnVisualizarP.setBackground(new java.awt.Color(255, 166, 166));
        btnVisualizarP.setForeground(new java.awt.Color(66, 33, 99));
        btnVisualizarP.setText("Visualizar");
        btnVisualizarP.setToolTipText("Visualizar Pedido");
        btnVisualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarPActionPerformed(evt);
            }
        });

        btnAddP.setBackground(new java.awt.Color(255, 166, 166));
        btnAddP.setForeground(new java.awt.Color(66, 33, 99));
        btnAddP.setText("Adicionar");
        btnAddP.setToolTipText("Adicionar prato ao pedido");
        btnAddP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPActionPerformed(evt);
            }
        });

        lblTamanhoP.setForeground(new java.awt.Color(66, 33, 99));
        lblTamanhoP.setText("Tamanho:");

        lblQtdP.setForeground(new java.awt.Color(66, 33, 99));
        lblQtdP.setText("Quantidade:");

        cbbTamanhoP.setBackground(new java.awt.Color(255, 166, 166));
        cbbTamanhoP.setForeground(new java.awt.Color(66, 33, 99));
        cbbTamanhoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tamanho", "Pequeno", "Médio", "Grande" }));
        cbbTamanhoP.setToolTipText("Selecione o tamanho do prato");

        txtQtdP.setBackground(new java.awt.Color(255, 166, 166));
        txtQtdP.setForeground(new java.awt.Color(66, 33, 99));
        txtQtdP.setText("1");
        txtQtdP.setToolTipText("Digite a quantidade de pratos");

        lblSubtotalP.setForeground(new java.awt.Color(66, 33, 99));

        lblErroQtdP.setForeground(new java.awt.Color(204, 0, 0));

        lblErroTamP.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlPrimaveraLayout = new javax.swing.GroupLayout(pnlPrimavera);
        pnlPrimavera.setLayout(pnlPrimaveraLayout);
        pnlPrimaveraLayout.setHorizontalGroup(
            pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addComponent(pnlTituloP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrimaveraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDescricaoP, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE))
                    .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                        .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(btnVoltarP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVisualizarP))
                            .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblQtdP)
                                    .addComponent(lblTamanhoP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                                        .addComponent(cbbTamanhoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErroTamP, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSubtotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                                        .addComponent(txtQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErroQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        pnlPrimaveraLayout.setVerticalGroup(
            pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                        .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPrimaveraLayout.createSequentialGroup()
                                .addComponent(pnlTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTamanhoP)
                                        .addComponent(cbbTamanhoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblErroTamP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblSubtotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtdP)
                            .addComponent(txtQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblErroQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrimaveraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarP)
                    .addComponent(btnAddP)
                    .addComponent(btnVisualizarP))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        lpnPrincipal.setLayer(pnlVerao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(pnlOutono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(pnlInverno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnPrincipal.setLayer(pnlPrimavera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnPrincipalLayout = new javax.swing.GroupLayout(lpnPrincipal);
        lpnPrincipal.setLayout(lpnPrincipalLayout);
        lpnPrincipalLayout.setHorizontalGroup(
            lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerao, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlOutono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlInverno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPrimavera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        lpnPrincipalLayout.setVerticalGroup(
            lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerao, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlOutono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlInverno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(lpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPrimavera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(976, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void jScrollPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseClicked

    }//GEN-LAST:event_jScrollPane6MouseClicked
    /**
     * Esse metodo eh essencial, ele eh responsavel por construir o pedido
     * @param estacao
     * @param lblSubtotal
     * @param lblErroQtd
     * @param lblErroTam
     * @param cbbTamanho
     * @param txtQtd
     * @param cardapio
     * @param btnVisualizar 
     */
    private void addPrato(JTable estacao, JLabel lblSubtotal, JLabel lblErroQtd,
                          JLabel lblErroTam, JComboBox cbbTamanho, JTextField txtQtd,
                          ArrayList cardapio, JButton btnVisualizar){
        int i = estacao.getSelectedRow();
        boolean add = true;   
        ItemPedido item = new ItemPedido();
        
        try{
            if(i >= 0 && i < cardapio.size()){
                lblSubtotal.setText("");
                if(!txtQtd.getText().equals("") && Integer.parseInt(txtQtd.getText()) > 0 &&
                   cbbTamanho.getSelectedIndex() != 0){
                    Prato prato = (Prato) cardapio.get(i);
                    
                    for(Object ip: pedido.getItemPedido()){
                        ItemPedido it = (ItemPedido) ip;
                        if(it.getPrato().getNumPrato() == prato.getNumPrato() && 
                           it.getTamanho().equals(cbbTamanho.getSelectedItem().toString())){
                            it.setQtd((byte) (it.getQtd() + Integer.parseInt(txtQtd.getText())));
                            it.setSubtotal(it.getSubtotal() + Integer.parseInt(txtQtd.getText()) * prato.getPreco());
                            add = false;
                            lblSubtotal.setText("Subtotal: R$" + String.format("%.2f", it.getSubtotal()));
                            break;
                        }else{
                            add = true;
                        }
                    }
                    if(add){
                        item.setQtd((byte) Integer.parseInt(txtQtd.getText()));
                        item.setTamanho(cbbTamanho.getSelectedItem().toString());
                        item.setPrato(prato);
                        item.setSubtotal(Integer.parseInt(txtQtd.getText()) * prato.getPreco());
                        lblSubtotal.setForeground(new Color(66,33,99));
                        lblSubtotal.setText("Subtotal: R$" + String.format("%.2f", item.getSubtotal()));
                        cbbTamanho.setSelectedIndex(0);
                        txtQtd.setText("1");
                        pedido.getItemPedido().add(item);
                        btnVisualizar.setEnabled(true);
                        
                    }
                    lblErroTam.setText("");
                    lblErroQtd.setText("");

                }else if(txtQtd.getText().equals("") || Integer.parseInt(txtQtd.getText()) <= 0){
                    lblErroQtd.setForeground(Color.red);
                    lblErroQtd.setText("Valor inválido");
                    lblErroTam.setText("");
                    
                }else if(cbbTamanho.getSelectedIndex() == 0){
                    lblErroTam.setForeground(Color.red);
                    lblErroTam.setText("Escolha o tamanho");
                    lblErroQtd.setText("");

                }
            }else{
                lblSubtotal.setForeground(Color.red);
                lblSubtotal.setText("Escolha um prato");
            }
         
        }catch(NumberFormatException e){
            lblErroQtd.setForeground(Color.red);
            lblErroQtd.setText("Valor inválido");
        }
    }
    /**
     * Basicamente carrega a tabela que sera exibida na tela. Esse metodo eh usado em defineEstacao()
     * @param estacao
     * @param tabela 
     */
    public void carregarCardapio(String estacao, JTable tabela){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nome do Prato",
                                                         "Preço", "Tempo de Preparo"}, 0);
        for(Prato p: pratos){
            if(p.getEstacao().equals(estacao)){
                Object linha[] = new Object[]{p.getNomePrato(), String.format("%.2f", p.getPreco()),
                                              p.getTempoPreparo()};
                modelo.addRow(linha);
            }
        }
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(300);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setResizable(false);
    }
    /**
     * Esse metodo recebe dia e mes e define qual tela devera ser exibida
     * @param dia
     * @param mes 
     */
    private void defineEstacao(int dia, int mes){
        if((mes == 3 && dia >= 21) || (mes > 3 && mes < 6) || (mes == 6 && dia <= 21)){
            pnlOutono.setVisible(true);
            getContentPane().setBackground(new java.awt.Color(255,255,180));
            carregarCardapio("outono", tblOutono);
            jScrollPane5.getViewport().setBackground(new Color(255,255,180));
            tblOutono.setFillsViewportHeight(true);
            setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/autumn32.png")).getImage());
            
        } else if((mes == 6 && dia >= 21) || (mes > 6 && mes < 9) || (mes == 9 && dia <= 23)){
            pnlInverno.setVisible(true);
            getContentPane().setBackground(new java.awt.Color(204,255,255));
            carregarCardapio("inverno", tblInverno);
            jScrollPane6.getViewport().setBackground(new Color(204,255,255));
            tblInverno.setFillsViewportHeight(true);
            setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/winter32.png")).getImage());
            
        } else if((mes == 9 && dia >= 21) || (mes > 9 && mes < 12) || (mes == 12 && dia <= 21)){
            pnlPrimavera.setVisible(true);
            getContentPane().setBackground(new java.awt.Color(255,204,204));
            carregarCardapio("primavera", tblPrimavera);
            jScrollPane7.getViewport().setBackground(new Color(255,204,204));
            tblPrimavera.setFillsViewportHeight(true);
            setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/spring32.png")).getImage());
            
        } else{
            pnlVerao.setVisible(true);
            getContentPane().setBackground(new java.awt.Color(255,204,153));
            carregarCardapio("verao", tblVerao);
            jScrollPane1.getViewport().setBackground(new Color(255,204,153));
            tblVerao.setFillsViewportHeight(true);
            setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/summer32.png")).getImage());
        }
    }
    
    private void tblInvernoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvernoMouseClicked
        int i = tblInverno.getSelectedRow();
        
        if(i >= 0 && i < inverno.size()){
            txtDescricaoI.setText(inverno.get(i).getDescricao());
            txtDescricaoI.setEditable(false);
        }
    }//GEN-LAST:event_tblInvernoMouseClicked

    private void btnVoltarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarVActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarVActionPerformed

    private void btnAddVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVActionPerformed
        addPrato(tblVerao, lblSubtotalV, lblErroQtdV, lblErroTamV, cbbTamanhoV, txtQtdV, verao, btnVisualizarV);
    }//GEN-LAST:event_btnAddVActionPerformed

    private void btnVisualizarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarVActionPerformed
        new TelaPedido().setVisible(true);
    }//GEN-LAST:event_btnVisualizarVActionPerformed

    private void btnVisualizarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarOActionPerformed
        new TelaPedido().setVisible(true);
    }//GEN-LAST:event_btnVisualizarOActionPerformed

    private void btnVisualizarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarIActionPerformed
        ArrayList<Pedido> pedidos = new ArrayList<>();
        pedidos.add(pedido);
        conta.setPedidos(pedidos);
        new TelaPedido().setVisible(true);
        
    }//GEN-LAST:event_btnVisualizarIActionPerformed

    private void btnVisualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarPActionPerformed
        new TelaPedido().setVisible(true);
    }//GEN-LAST:event_btnVisualizarPActionPerformed

    private void btnVoltarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarOActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarOActionPerformed

    private void btnVoltarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarIActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarIActionPerformed

    private void btnVoltarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarPActionPerformed

    private void btnAddPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPActionPerformed
        addPrato(tblPrimavera, lblSubtotalP, lblErroQtdP, lblErroTamP, cbbTamanhoP, txtQtdP, primavera, btnVisualizarP);
    }//GEN-LAST:event_btnAddPActionPerformed

    private void tblVeraoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeraoMouseClicked
        int i = tblVerao.getSelectedRow();
        
        if(i >= 0 && i < verao.size()){
            txtDescricaoV.setText(verao.get(i).getDescricao());
            txtDescricaoV.setEditable(false);
        }
    }//GEN-LAST:event_tblVeraoMouseClicked

    private void btnAddIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIActionPerformed
        addPrato(tblInverno, lblSubtotalI, lblErroQtdI, lblErroTamI, cbbTamanhoI, txtQtdI, inverno, btnVisualizarI);
    }//GEN-LAST:event_btnAddIActionPerformed

    private void btnAddOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOActionPerformed
        addPrato(tblOutono, lblSubtotalO, lblErroQtdO, lblErroTamO, cbbTamanhoO, txtQtdO, outono, btnVisualizarO);
    }//GEN-LAST:event_btnAddOActionPerformed

    private void tblOutonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOutonoMouseClicked
        int i = tblOutono.getSelectedRow();
        
        if(i >= 0 && i < outono.size()){
            txtDescricaoO.setText(outono.get(i).getDescricao());
            txtDescricaoO.setEditable(false);
        }
    }//GEN-LAST:event_tblOutonoMouseClicked

    private void tblPrimaveraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrimaveraMouseClicked
        int i = tblPrimavera.getSelectedRow();
        
        if(i >= 0 && i < primavera.size()){
            txtDescricaoP.setText(primavera.get(i).getDescricao());
            txtDescricaoP.setEditable(false);
        }
    }//GEN-LAST:event_tblPrimaveraMouseClicked
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddI;
    private javax.swing.JButton btnAddO;
    private javax.swing.JButton btnAddP;
    private javax.swing.JButton btnAddV;
    private javax.swing.JButton btnVisualizarI;
    private javax.swing.JButton btnVisualizarO;
    private javax.swing.JButton btnVisualizarP;
    private javax.swing.JButton btnVisualizarV;
    private javax.swing.JButton btnVoltarI;
    private javax.swing.JButton btnVoltarO;
    private javax.swing.JButton btnVoltarP;
    private javax.swing.JButton btnVoltarV;
    private javax.swing.JComboBox<String> cbbTamanhoI;
    private javax.swing.JComboBox<String> cbbTamanhoO;
    private javax.swing.JComboBox<String> cbbTamanhoP;
    private javax.swing.JComboBox<String> cbbTamanhoV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblErroQtdI;
    private javax.swing.JLabel lblErroQtdO;
    private javax.swing.JLabel lblErroQtdP;
    private javax.swing.JLabel lblErroQtdV;
    private javax.swing.JLabel lblErroTamI;
    private javax.swing.JLabel lblErroTamO;
    private javax.swing.JLabel lblErroTamP;
    private javax.swing.JLabel lblErroTamV;
    private javax.swing.JLabel lblQtdI;
    private javax.swing.JLabel lblQtdO;
    private javax.swing.JLabel lblQtdP;
    private javax.swing.JLabel lblQtdV;
    private javax.swing.JLabel lblSubtotalI;
    private javax.swing.JLabel lblSubtotalO;
    private javax.swing.JLabel lblSubtotalP;
    private javax.swing.JLabel lblSubtotalV;
    private javax.swing.JLabel lblTamanhoI;
    private javax.swing.JLabel lblTamanhoO;
    private javax.swing.JLabel lblTamanhoP;
    private javax.swing.JLabel lblTamanhoV;
    private javax.swing.JLabel lblTituloI;
    private javax.swing.JLabel lblTituloO;
    private javax.swing.JLabel lblTituloP;
    private javax.swing.JLabel lblTituloV;
    private javax.swing.JLayeredPane lpnPrincipal;
    private javax.swing.JPanel pnlInverno;
    private javax.swing.JPanel pnlOutono;
    private javax.swing.JPanel pnlPrimavera;
    private javax.swing.JPanel pnlTituloI;
    private javax.swing.JPanel pnlTituloO;
    private javax.swing.JPanel pnlTituloP;
    private javax.swing.JPanel pnlTituloV;
    private javax.swing.JPanel pnlVerao;
    private javax.swing.JTable tblInverno;
    private javax.swing.JTable tblOutono;
    private javax.swing.JTable tblPrimavera;
    private javax.swing.JTable tblVerao;
    private javax.swing.JTextArea txtDescricaoI;
    private javax.swing.JTextArea txtDescricaoO;
    private javax.swing.JTextArea txtDescricaoP;
    private javax.swing.JTextArea txtDescricaoV;
    private javax.swing.JTextField txtQtdI;
    private javax.swing.JTextField txtQtdO;
    private javax.swing.JTextField txtQtdP;
    private javax.swing.JTextField txtQtdV;
    // End of variables declaration//GEN-END:variables
}
