
package telas;

import fourseasoning.ItemPedido;
import fourseasoning.Pedido;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import static telas.TelaConta.conta;
import javax.swing.table.DefaultTableModel;
import static telas.TelaConta.pedido;
import static telas.TelaMesa.tela;

public class TelaPedido extends javax.swing.JFrame {
 
    
    public TelaPedido() {
        initComponents();
        // Troca a cor do JFrame
        Color cor = new Color(217,220,235);
        getContentPane().setBackground(cor);
        jScrollPane1.getViewport().setBackground(cor);
        tblPedido.setFillsViewportHeight(true);
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        btnFinalizar = new JButton("<html><center>Finalizar<br>Pedido</html>");
        btnContinuar = new JButton("<html><center>Continuar<br>Pedido</html>");
        lblTotal = new javax.swing.JLabel();
        lblTotalCDesconto = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        btnRemover.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedido");
        setBackground(new java.awt.Color(217, 220, 235));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/prato32.png")).getImage());

        jScrollPane1.setBackground(new java.awt.Color(217, 220, 235));
        jScrollPane1.setForeground(new java.awt.Color(66, 33, 99));

        tblPedido.setBackground(new java.awt.Color(217, 220, 235));
        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tamanho", "Quantidade", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedido);

        btnFinalizar.setBackground(new java.awt.Color(204, 204, 230));
        btnFinalizar.setForeground(new java.awt.Color(66, 33, 99));
        btnFinalizar.setToolTipText("Finalizar pedido");
        btnFinalizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(204, 204, 230));
        btnContinuar.setForeground(new java.awt.Color(66, 33, 99));
        btnContinuar.setToolTipText("Continuar pedido");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblTotal.setBackground(new java.awt.Color(217, 220, 235));
        lblTotal.setForeground(new java.awt.Color(66, 33, 99));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblTotalCDesconto.setBackground(new java.awt.Color(217, 220, 235));
        lblTotalCDesconto.setForeground(new java.awt.Color(66, 33, 99));
        lblTotalCDesconto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnRemover.setBackground(new java.awt.Color(204, 204, 230));
        btnRemover.setForeground(new java.awt.Color(66, 33, 99));
        btnRemover.setText("Remover");
        btnRemover.setToolTipText("Remover prato selecionado");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinalizar)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalCDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnRemover)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(202, 202, 202))
        );

        setSize(new java.awt.Dimension(976, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * quando um prato eh selecionado o botao para remover sera exibido
     * @param evt 
     */
    private void tblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidoMouseClicked
        int i = tblPedido.getSelectedRow();
        
        if(i >= 0 && i < pedido.getItemPedido().size()){
            btnRemover.setVisible(true);
        }
    }//GEN-LAST:event_tblPedidoMouseClicked
    /**
     * metodo para remover um prato do pedido
     * @param evt 
     */
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int i = tblPedido.getSelectedRow();
        pedido.getItemPedido().remove(i);
        carregarTabela();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed
    /**
     * metodo que finaliza o pedido, ele tambem atualiza o banco de dados, pois
     * eh necessario que fique registrado que a fatura do pedido nao foi paga ainda,
     * ela so podera ser paga na tela da conta
     * @param evt 
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        tela.dispose();
        
        conta.setPago(false);
        if(conta.getCategoria().equals("Premium") || 
           conta.getCategoria().equals("Standard")){
            conta.setFatura(pedido.calcularTotalCDesconto() + conta.getFatura());
            
        }else{
            conta.setFatura(pedido.calcularTotal() + conta.getFatura());
        
        }
        TelaConta.gerente.marcarPonto();
        this.dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed
    /**
     * metodo para carregar a tabela com todos pedidos feitos pela conta
     */
    public void carregarTabela(){
        // Na versao anterior o DefaultTableModel estava declarado como global e isso causou erros
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nome do Prato",
                                   "Tamanho do Prato", "Quantidade", "Subtotal"},0);
        ArrayList<Pedido> pedidos = conta.getPedidos();
        for(Pedido p: pedidos){
            ArrayList<ItemPedido> items = p.getItemPedido();

            for(ItemPedido item: items){
                Object linha[] = new Object[]{item.getPrato().getNomePrato(), item.getTamanho(),
                                              item.getQtd(), String.format("%.2f", item.getSubtotal())};
                modelo.addRow(linha);
            }
        }
        tblPedido.setModel(modelo);
        
        if(conta.getCategoria().equals("Premium") || 
           conta.getCategoria().equals("Standard")){
            lblTotal.setForeground(Color.red);
            lblTotalCDesconto.setForeground(new Color(0,120,56));
            lblTotal.setText("Total: R$" + String.format("%.2f", pedido.calcularTotal()));
            lblTotalCDesconto.setText("Total após desconto: R$" + String.format("%.2f", pedido.calcularTotalCDesconto()));
            
        }else{
            lblTotal.setForeground(new Color(0,120,56));
            lblTotal.setText("Total: R$" + String.format("%.2f", pedido.calcularTotal()));
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPedido().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalCDesconto;
    private javax.swing.JTable tblPedido;
    // End of variables declaration//GEN-END:variables
}
