/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import fourseasoning.Funcionario;
import static fourseasoning.Funcionario.getFuncionarios;
import static fourseasoning.Funcionario.getGerente;
import java.awt.Color;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author aluno
 */
public class TelaFuncionario extends javax.swing.JFrame {
    
    static ArrayList<Funcionario> funcionarios = getFuncionarios();
    static Funcionario gerente = getGerente();
    
    static Funcionario func = new Funcionario();
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
        // Troca a cor do JFrame
        Color cor = new Color(217,220,235);
        getContentPane().setBackground(cor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtCpf = new javax.swing.JTextField();
        lblErro = new javax.swing.JLabel();
        lblErro.setVisible(false);
        btnVoltar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        pnlInfos = new javax.swing.JPanel();
        pnlInfos.setVisible(false);
        btnChegada = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnVisualizar.setVisible(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDados = new javax.swing.JList<>();
        lstDados.setVisible(false);
        jbtGerente = new javax.swing.JButton();
        jbtGerente.setVisible(false);
        lblPonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionários");
        setBackground(new java.awt.Color(217, 220, 235));
        setForeground(new java.awt.Color(217, 220, 235));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios64.png")).getImage());
        setSize(new java.awt.Dimension(960, 640));

        pnlTitulo.setBackground(new java.awt.Color(217, 220, 235));
        pnlTitulo.setForeground(new java.awt.Color(217, 220, 235));

        lblTitulo.setFont(new java.awt.Font("Segoe Print", 1, 50)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(66, 33, 99));
        lblTitulo.setText("4 Seasoning");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(39, 39, 39))
        );

        pnlLogin.setBackground(new java.awt.Color(217, 220, 235));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(66, 33, 99))); // NOI18N
        pnlLogin.setForeground(new java.awt.Color(217, 220, 235));

        lblCpf.setBackground(new java.awt.Color(204, 204, 230));
        lblCpf.setForeground(new java.awt.Color(66, 33, 99));
        lblCpf.setText("CPF:");

        lblSenha.setBackground(new java.awt.Color(204, 204, 230));
        lblSenha.setForeground(new java.awt.Color(66, 33, 99));
        lblSenha.setText("Senha:");

        txtSenha.setBackground(new java.awt.Color(204, 204, 230));
        txtSenha.setForeground(new java.awt.Color(66, 33, 99));
        txtSenha.setToolTipText("Digite sua senha");

        txtCpf.setBackground(new java.awt.Color(204, 204, 230));
        txtCpf.setForeground(new java.awt.Color(66, 33, 99));
        txtCpf.setToolTipText("Digite seu CPF");
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        lblErro.setForeground(new java.awt.Color(204, 0, 0));
        lblErro.setText("Senha ou CPF incorreto");

        btnVoltar.setBackground(new java.awt.Color(204, 204, 230));
        btnVoltar.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar16.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(204, 204, 230));
        btnLogin.setForeground(new java.awt.Color(66, 33, 99));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok16.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Fazer login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblCpf))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSenha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErro)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGap(0, 37, Short.MAX_VALUE)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnLogin))
                .addGap(21, 21, 21))
        );

        pnlInfos.setBackground(new java.awt.Color(217, 220, 235));
        pnlInfos.setForeground(new java.awt.Color(217, 220, 235));

        btnChegada.setBackground(new java.awt.Color(204, 204, 230));
        btnChegada.setForeground(new java.awt.Color(66, 33, 99));
        btnChegada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pontoChegada48.png"))); // NOI18N
        btnChegada.setToolTipText("Registrar hora de chegada");
        btnChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChegadaActionPerformed(evt);
            }
        });

        btnSaida.setBackground(new java.awt.Color(204, 204, 230));
        btnSaida.setForeground(new java.awt.Color(66, 33, 99));
        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pontoSaida48.png"))); // NOI18N
        btnSaida.setToolTipText("Registrar hora de saída");
        btnSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        btnVisualizar.setBackground(new java.awt.Color(204, 204, 230));
        btnVisualizar.setForeground(new java.awt.Color(217, 220, 235));
        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho16.png"))); // NOI18N
        btnVisualizar.setToolTipText("Visualizar dados");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        lstDados.setBackground(new java.awt.Color(204, 204, 230));
        lstDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstDados.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lstDados.setForeground(new java.awt.Color(66, 33, 99));
        lstDados.setSelectionBackground(new java.awt.Color(66, 33, 99));
        jScrollPane1.setViewportView(lstDados);

        jbtGerente.setBackground(new java.awt.Color(204, 204, 230));
        jbtGerente.setForeground(new java.awt.Color(66, 33, 99));
        jbtGerente.setText("Gerente");
        jbtGerente.setToolTipText("Ir para tela de gerente");
        jbtGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGerenteActionPerformed(evt);
            }
        });

        lblPonto.setForeground(new java.awt.Color(66, 33, 99));

        javax.swing.GroupLayout pnlInfosLayout = new javax.swing.GroupLayout(pnlInfos);
        pnlInfos.setLayout(pnlInfosLayout);
        pnlInfosLayout.setHorizontalGroup(
            pnlInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfosLayout.createSequentialGroup()
                        .addComponent(btnChegada)
                        .addGap(38, 38, 38)
                        .addComponent(btnSaida)
                        .addGap(159, 159, 159)
                        .addComponent(jbtGerente))
                    .addGroup(pnlInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlInfosLayout.createSequentialGroup()
                            .addComponent(btnVisualizar)
                            .addGap(18, 18, 18)
                            .addComponent(lblPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(266, 266, 266))
        );
        pnlInfosLayout.setVerticalGroup(
            pnlInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChegada)
                    .addComponent(btnSaida)
                    .addComponent(jbtGerente))
                .addGap(52, 52, 52)
                .addGroup(pnlInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(960, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed
    /**
     * metodo para fazer o login
     * @param evt 
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String senha = new String(txtSenha.getPassword());
        String cpf = txtCpf.getText();
        boolean flag = false;
        
        for(Funcionario funcionario: funcionarios){
            if(funcionario.getCpf().equals(cpf) && funcionario.isSenha(senha)){
                func = funcionario;
                pnlInfos.setVisible(true);
                pnlLogin.setVisible(false);
                flag = true;
                if(getGerente().getCpf().equals(cpf) && getGerente().isSenha(senha)){
                    jbtGerente.setVisible(true);
                }
            }
        }
        
        if(!flag){
            lblErro.setVisible(true);
            txtCpf.setText("");
            txtSenha.setText("");
        }else{
            lblTitulo.setText("Olá, " + func.getNome().split(" ")[0]);
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    /**
     * metodo para registrar o horario de chegada do funcionario
     * @param evt 
     */
    private void btnChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChegadaActionPerformed
        func.setPontoChegada(LocalDateTime.now());
        func.marcarPonto();
        lblPonto.setText("Ponto de chegada " + String.format("%02d", LocalDateTime.now().getHour()) + 
                         ":" + String.format("%02d", LocalDateTime.now().getMinute()));
        
        btnVisualizar.setVisible(true);        
    }//GEN-LAST:event_btnChegadaActionPerformed
    /**
     * metodo para registrar o horario de saida do funcionario
     * @param evt 
     */
    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
       
        func.setPontoSaida(LocalDateTime.now());
        func.calcularBancoDeHoras();
        lblPonto.setText("Ponto de saída " + String.format("%02d", LocalDateTime.now().getHour()) + 
                         ":" + String.format("%02d", LocalDateTime.now().getMinute()));
        
        btnVisualizar.setVisible(true);        
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
    /**
     * metodo que exibe os dados do funcionario em uma lista
     * @param evt 
     */
    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        lstDados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] dados = func.toString().split("\n");
            public int getSize() { return dados.length; }
            public String getElementAt(int i) { return dados[i]; }
        });
        jScrollPane1.setViewportView(lstDados);
        lstDados.setVisible(true);
        
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void jbtGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGerenteActionPerformed
        new TelaGerente().setVisible(true);
    }//GEN-LAST:event_jbtGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChegada;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtGerente;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblPonto;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstDados;
    private javax.swing.JPanel pnlInfos;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
