/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import fourseasoning.Funcionario;
import java.awt.Font;
import javax.swing.JButton;

/**
 *
 * @author leorb
 */
public class TelaPrincipal extends javax.swing.JFrame {
    static Funcionario f = new Funcionario();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        f.carregarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        btnCliente.setHorizontalTextPosition(JButton.CENTER);
        btnCliente.setVerticalTextPosition(JButton.TOP);
        btnCliente.setFont(new Font("Segoe Print",Font.BOLD,12));
        btnCliente.setIconTextGap(10);
        btnFuncionario = new javax.swing.JButton();
        btnFuncionario.setHorizontalTextPosition(JButton.CENTER);
        btnFuncionario.setVerticalTextPosition(JButton.TOP);
        btnFuncionario.setFont(new Font("Segoe Print",Font.BOLD,12));
        btnFuncionario.setIconTextGap(10);
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4 Seasoning");
        setBackground(new java.awt.Color(210, 179, 210));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(210, 179, 210));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/seasons32.png")).getImage());
        setMaximumSize(new java.awt.Dimension(1920, 1080));

        pnlPrincipal.setBackground(new java.awt.Color(217, 220, 235));
        pnlPrincipal.setForeground(new java.awt.Color(217, 220, 235));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(960, 640));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(960, 640));
        pnlPrincipal.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe Print", 1, 50)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(66, 33, 99));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setLabelFor(pnlPrincipal);
        lblTitulo.setText("4 Seasoning");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlPrincipal.add(lblTitulo);
        lblTitulo.setBounds(283, 40, 470, 59);

        btnCliente.setBackground(new java.awt.Color(204, 204, 230));
        btnCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(66, 33, 99));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente64.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setToolTipText("Cliente");
        btnCliente.setPreferredSize(new java.awt.Dimension(103, 23));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCliente);
        btnCliente.setBounds(374, 288, 141, 120);

        btnFuncionario.setBackground(new java.awt.Color(204, 204, 230));
        btnFuncionario.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnFuncionario.setForeground(new java.awt.Color(66, 33, 99));
        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios64.png"))); // NOI18N
        btnFuncionario.setText("Funcionário");
        btnFuncionario.setToolTipText("Funcionário");
        btnFuncionario.setMaximumSize(new java.awt.Dimension(141, 70));
        btnFuncionario.setMinimumSize(new java.awt.Dimension(141, 70));
        btnFuncionario.setPreferredSize(new java.awt.Dimension(103, 23));
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnFuncionario);
        btnFuncionario.setBounds(521, 288, 141, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Untitled.png"))); // NOI18N
        pnlPrincipal.add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        /**
         * Se o botao de funcionario for clicado abre a tela de funcionario
         */
        new TelaFuncionario().setVisible(true);
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        /**
         * * Se o botao de conta for clicado abre a tela de conta
         */
        new TelaConta().setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
