package telas;

import java.awt.Color;
import static fourseasoning.Funcionario.getMesas;
import fourseasoning.Mesa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static telas.TelaConta.conta;
 
public class TelaMesa extends javax.swing.JFrame {
    static TelaPrato tela = new TelaPrato();
    static ArrayList<Mesa> mesas = getMesas();
    /**
     * Creates new form TelaMesa
     */
    public TelaMesa() {
        initComponents();
        // Troca a cor do JFrame
        Color cor = new Color(217,220,235);
        getContentPane().setBackground(cor);
        carregarTabela();
        jScrollPane1.getViewport().setBackground(cor);
        tblMesas.setFillsViewportHeight(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        btnPedido = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mesa");
        setBackground(new java.awt.Color(217, 220, 235));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/mesa32.png")).getImage());

        jScrollPane1.setBackground(new java.awt.Color(217, 220, 235));
        jScrollPane1.setForeground(new java.awt.Color(66, 33, 99));
        jScrollPane1.setToolTipText("Selecione uma mesa");

        tblMesas.setBackground(new java.awt.Color(217, 220, 235));
        tblMesas.setForeground(new java.awt.Color(66, 33, 99));
        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº da mesa", "Quantidade de cadeiras", "Área", "Disponibilidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMesas.setGridColor(new java.awt.Color(0, 0, 0));
        tblMesas.setSelectionBackground(new java.awt.Color(66, 33, 99));
        tblMesas.setSelectionForeground(new java.awt.Color(217, 220, 235));
        jScrollPane1.setViewportView(tblMesas);
        if (tblMesas.getColumnModel().getColumnCount() > 0) {
            tblMesas.getColumnModel().getColumn(0).setResizable(false);
            tblMesas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblMesas.getColumnModel().getColumn(1).setResizable(false);
            tblMesas.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblMesas.getColumnModel().getColumn(2).setResizable(false);
            tblMesas.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblMesas.getColumnModel().getColumn(3).setResizable(false);
            tblMesas.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        btnPedido.setBackground(new java.awt.Color(204, 204, 230));
        btnPedido.setForeground(new java.awt.Color(66, 33, 99));
        btnPedido.setText("Fazer pedido");
        btnPedido.setToolTipText("Fazer pedido");
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(204, 204, 230));
        btnVoltar.setForeground(new java.awt.Color(66, 33, 99));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedido)
                .addGap(0, 389, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedido)
                    .addComponent(btnVoltar))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(976, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nº da mesa",
                                                         "Quantidade de cadeiras",
                                                         "Área","Disponibilidade"},0);
        for(Mesa m: mesas){
            Object linha[] = new Object[]{m.getNum(), m.getQtdCadeiras(), m.getArea(),
                                          m.getDisponibilidade() == true ? "Disponível" : "Indisponível"};
            modelo.addRow(linha);
        }
        tblMesas.setModel(modelo);
    }
    
    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        /**
         * Quando o botao pedido é apertado, algumas verificaçoes sao feitas
         * 1º: pegamos a linha selecionada e atribuimos a variavel i
         * 2º: verificamos se o valor de esta em um intervalo valido
         * 3º: verificamos se a mesa esta disponivel, se sim, usamos o metodo setMesa
         * para atribuir essa mesa ao cliente, definimos a mesa como indisponivel e 
         * mostramos a TelaPedido, se a mesa estiver disponivel, mostramos um JOptionPane
         * com a mensagem para o usuario escolher outra mesa
         */
        int i = tblMesas.getSelectedRow();
        
        if(i >= 0 && i < mesas.size()){
            if(mesas.get(i).getDisponibilidade()){
                conta.setMesa(mesas.get(i));
                mesas.get(i).setDisponibilidade(false);
                tela.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Mesa indisponível\nEscolha outra mesa",
                                              "Aviso",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMesas;
    // End of variables declaration//GEN-END:variables
}
